---
service: es-enrichment-sg
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-enrichment-wrangler:
    name: es-enrichment-wrangler
    handler: enrichment_wrangler.lambda_handler
    package:
      include:
        - enrichment_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 1
      bucket_name: results-s3-bucket
      identifier_column: responder_id
      in_file_name: Sandy_Merged.json
      incoming_message_group: ingest-takeon-data-out
      method_name: es-enrichment-method
      out_file_name: enrichment_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: enrichment-out
      marine_mismatch_check: true
      period_column: period

  deploy-enrichment-method:
    name: es-enrichment-method
    handler: enrichment_method.lambda_handler
    package:
      include:
        - enrichemnt_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      bucket_name: results-s3-bucket

plugins:
  - serverless-latest-layer-version
