---
service: es-enrichment-sg
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-enrichment-wrangler:
    name: es-enrichment-wrangler
    handler: enrichment_wrangler.lambda_handler
    package:
      include:
        - enrichment_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      identifier_column: responder_id
      in_file_name: ingest_out.json
      incoming_message_group: ingest-takeon-data-out
      method_name: es-enrichment-method
      out_file_name: enrichment_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: enrichment-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-enrichment-method:
    name: es-enrichment-method
    handler: enrichment_method.lambda_handler
    package:
      include:
        - enrichemnt_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      bucket_name: results-s3-bucket
      county_lookup_column_1: county_name
      county_lookup_column_2: region
      county_lookup_column_3: county
      county_lookup_column_4: marine
      county_lookup_file: county_lookup.json
      identifier_column: responder_id
      marine_mismatch_check: true
      missing_county_check: true
      missing_region_check: true
      period_column: period
      responder_lookup_file: responder_county_lookup_prod.json
